import { money, evidenceNames, reasons, services } from './journey.js?v=journey-v2';

export const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const attrs=(action,value='')=>`data-action="${action}" data-value="${esc(value)}"`;
export const button=(label,action,value='',kind='primary',extra='')=>`<button type="button" class="ui-button ${kind}" ${attrs(action,value)} ${extra}>${label}</button>`;
const row=(title,subtitle,action,value='',icon='›')=>`<button type="button" class="ui-row" ${attrs(action,value)}><span><strong>${title}</strong>${subtitle?`<small>${subtitle}</small>`:''}</span><span class="row-symbol" aria-hidden="true">${icon}</span></button>`;
const note=(text,kind='mint')=>`<div class="ui-note ${kind}">${text}</div>`;
const badge=text=>`<span class="ui-badge">${text}</span>`;
const card=html=>`<section class="ui-card">${html}</section>`;
const heading=(title,subtitle='')=>`<h2>${title}</h2>${subtitle?`<p class="muted">${subtitle}</p>`:''}`;
const detail=(label,value)=>`<div class="detail-row"><span>${label}</span><strong>${value}</strong></div>`;
const prior=()=>card(`<p class="eyebrow">รายการก่อนหน้า · 20 ก.ย. 2569 · 10:24 น.</p><div class="recipient-line"><img src="./assets/journey/recipient.png" alt=""><div><strong>ผู้รับตัวอย่าง</strong><p>xxx-x-x6789-x</p></div></div><p class="money">50,000.00 <small>บาท</small></p>`);
const pending=m=>card(`<p class="eyebrow">รายการที่กำลังทำ · เงินยังไม่ออก</p>${detail('ผู้รับ','ผู้รับตัวอย่าง')}${detail('จำนวนเงิน',money(m.amountCents)+' บาท')}${detail('สถานะ',m.transferStatus==='cancelled'?'ยกเลิกแล้ว':'พักรายการไว้')}`);
const caseCard=m=>card(`${badge('กำลังตรวจสอบ')}<h3>SB-2026-00128</h3>${detail('รายการที่แจ้ง','50,000.00 บาท')}${detail('หลักฐาน',m.evidenceSet.size+' รายการ')}<p class="muted">เงินที่โอนไปก่อนหน้ายังอยู่ระหว่างตรวจสอบ</p>`);
const error=m=>`<p class="form-error" role="status" ${m.notice?'':'hidden'}>${esc(m.notice)}</p>`;
const homeButton=()=>button('กลับหน้าแรก','home','','secondary');

export function content(m){
  switch(m.route){
    case 'riskInfo':return heading('ทำไมจึงควรหยุดตรวจสอบ?')+card('<h3>ผู้รับรายใหม่</h3><p>เป็นผู้รับที่ยังไม่เคยโอนให้ในสถานการณ์ตัวอย่าง</p>')+card('<h3>ยอดสูงกว่าปกติ</h3><p>เป็นสัญญาณเตือนที่กำหนดไว้ในสไลด์สำหรับสาธิต ไม่ใช่การประเมินบัญชีจริง</p>')+note('คำตอบว่า “ไม่ใช่” ไม่ได้ยืนยันว่ารายการปลอดภัย ยังควรตรวจสอบผู้รับและช่องทางติดต่อ','amber')+button('ตรวจสอบสถานการณ์ก่อนโอน','risk')+button('กลับไปตรวจสอบข้อมูล','back','','secondary');
    case 'recipient':return heading('โอนเงินให้ใคร?','เลือกบัญชีตัวอย่างเพื่อเริ่มรายการ')+
      note('ใช้เฉพาะผู้รับสมมติในเดโม ไม่ต้องกรอกข้อมูลบัญชีจริง')+
      `<button type="button" class="ui-card recipient-choice" ${attrs('recipient-select')}><img src="./assets/journey/recipient.png" alt=""><span><strong>ผู้รับตัวอย่าง</strong><small>ธ.กสิกรไทย · xxx-x-x6789-x</small><em>ผู้รับรายใหม่</em></span><span aria-hidden="true">›</span></button>`+
      card(`<p class="eyebrow">บัญชีต้นทาง</p><h3>บัญชีของฉัน</h3><p>xxx-x-x2560-x</p><p class="muted">ยอดคงเหลือตัวอย่าง ${money(m.balanceCents)} บาท</p>`)+homeButton();
    case 'amount':return `<p class="eyebrow">โอนไปยัง</p><div class="recipient-line compact"><img src="./assets/journey/recipient.png" alt=""><div><strong>ผู้รับตัวอย่าง</strong><p>xxx-x-x6789-x</p></div></div>`+
      `<label class="amount-label" for="amount-input">จำนวนเงิน (บาท)</label><div class="amount-entry"><input id="amount-input" type="text" inputmode="decimal" maxlength="16" autocomplete="off" spellcheck="false" placeholder="0.00" aria-describedby="amount-help amount-error" value="${esc(m.amountRaw)}"><button type="button" class="amount-clear" ${attrs('amount-key','clear')} aria-label="ล้างจำนวนเงิน">×</button></div>`+
      `<p id="amount-help" class="small muted">ยอดคงเหลือตัวอย่าง ${money(m.balanceCents)} บาท</p><div class="preset-row">${[5000,50000,100000].map(v=>button(v.toLocaleString('en-US'),'amount-preset',String(v),'chip')).join('')}</div>`+
      `<p id="amount-error" class="form-error" role="status" ${m.notice?'':'hidden'}>${esc(m.notice)}</p><div class="number-pad" aria-label="แป้นจำนวนเงิน">${['1','2','3','4','5','6','7','8','9','.','0','backspace'].map(v=>button(v==='backspace'?'⌫':v,'amount-key',v,'key',v==='backspace'?'aria-label="ลบตัวเลขท้ายสุด"':'')).join('')}</div>`+
      button('ตรวจสอบข้อมูลการโอน','amount-next')+`<p class="small muted center">ค่าธรรมเนียม 0.00 บาท · ยังไม่โอนเงินในขั้นนี้</p>`;
    case 'cancel':return `<div class="result-mark amber">!</div>`+heading('ยกเลิกรายการนี้?','เงินในรายการนี้ยังไม่ได้ถูกโอนออก')+pending(m)+note('ยกเลิกเฉพาะรายการที่พักไว้ ไม่กระทบรายการที่โอนไปก่อนหน้า')+button('ยืนยันยกเลิกรายการ','cancel-yes','','danger')+button('กลับไปพักรายการ','back','','secondary');
    case 'cancelled':return `<div class="result-mark">✓</div>`+heading('ยกเลิกรายการแล้ว','เงินยังอยู่ในบัญชีของคุณ')+pending(m)+note('ถ้าเคยโอนไปก่อนหน้าและสงสัยว่าถูกหลอก คุณยังขอความช่วยเหลือได้')+button('ฉันอาจถูกหลอก','emergency','','danger')+homeButton();
    case 'transactions':return heading('รายการของฉัน')+
      (m.amountCents>0?row(`${money(m.amountCents)} บาท · ${m.transferStatus==='cancelled'?'ยกเลิกแล้ว':'ยังไม่โอนออก'}`,'รายการที่กำลังทำ → ผู้รับตัวอย่าง','transaction','pending'): '')+
      row('50,000.00 บาท · โอนไปก่อนหน้า','20 ก.ย. 2569 · ผู้รับตัวอย่าง','transaction','prior')+
      m.serviceReceipts.map(r=>row(`${services[r.kind].title} · ${money(r.amount)} บาท`,'รายการตัวอย่างที่ทำในเดโม','transaction',r.id)).join('')+
      (m.caseSubmitted?row('ติดตามเคส SB-2026-00128','กำลังตรวจสอบ · ไม่มีการยืนยันคืนเงิน','track'):note('รายการที่พักไว้จะไม่ถูกนับเป็นเงินที่โอนออกแล้ว'))+homeButton();
    case 'transaction':{
      if(m.transactionId==='pending')return heading('รายการที่กำลังทำ')+pending(m)+note('รายการนี้ไม่มีเงินออกจากบัญชี จึงแยกจากรายการก่อนหน้าที่ใช้แจ้งเหตุ')+(m.transferStatus==='cancelled'?'':button('กลับไปพักรายการ','go','hold'))+button('ดูรายการที่เคยโอนไปแล้ว','go','transactions','secondary')+homeButton();
      const receipt=m.serviceReceipts.find(r=>r.id===m.transactionId);
      if(receipt)return heading(services[receipt.kind].title+'ตัวอย่าง')+card(`${detail('สถานะ','สำเร็จในเดโมเท่านั้น')}${detail('จำนวนเงิน',money(receipt.amount)+' บาท')}${detail('หมายเลขอ้างอิง',receipt.id.toUpperCase())}`)+note('รายการนี้เป็นข้อมูลสมมติ ไม่มีการทำธุรกรรมกับธนาคารหรือผู้ให้บริการจริง')+button('ดูธุรกรรมทั้งหมด','go','transactions')+homeButton();
      return heading('รายการที่โอนไปก่อนหน้า')+prior()+note('เป็นรายการตัวอย่างที่เกิดก่อนเริ่มเดโม ไม่ใช่ยอดที่กำลังพักอยู่','amber')+(m.caseSubmitted?button('ติดตามเรื่องที่แจ้งไว้','track'):button('สงสัยรายการนี้ · ขอความช่วยเหลือ','emergency','','danger'))+button('ดูสลิปตัวอย่าง','evidence-open','slip','secondary');
    }
    case 'select':return heading('เลือกรายการที่เคยโอนไป','เงินที่โอนไปก่อนหน้ายังต้องตรวจสอบเพิ่มเติม')+
      `<button type="button" class="ui-card selectable ${m.selectedTxn?'selected':''}" ${attrs('select-prior')} aria-pressed="${m.selectedTxn}"><span class="selection-dot" aria-hidden="true">${m.selectedTxn?'✓':''}</span><span><strong>ผู้รับตัวอย่าง</strong><small>20 ก.ย. 2569 · 10:24 น.</small><b>50,000.00 บาท</b><small>xxx-x-x6789-x</small></span></button>`+
      (m.amountCents>0?row(`${money(m.amountCents)} บาท · เงินยังไม่ออก`,'รายการที่พักไว้ / ยกเลิก ไม่ใช่รายการที่แจ้ง','transaction','pending'):note('เลือกรายการก่อนหน้า 50,000 บาท เพื่อเดินเรื่องตามเคสในสไลด์'))+
      error(m)+button('กรอกรายละเอียดเหตุการณ์','report-details')+button('ติดต่อเจ้าหน้าที่ก่อน','contact','','secondary');
    case 'details':return heading('เกิดอะไรขึ้น?','เลือกเหตุการณ์ตัวอย่าง ไม่ต้องพิมพ์ข้อมูลส่วนตัว')+
      `<div class="choice-stack">${Object.entries(reasons).map(([key,label])=>button(`${m.reason===key?'✓ ':''}${label}`,'reason',key,`choice ${m.reason===key?'selected':''}`,`aria-pressed="${m.reason===key}" data-focus="reason-${key}"`)).join('')}</div>`+
      row('หลักฐานประกอบ '+m.evidenceSet.size+' รายการ','เลือกจากสลิปและภาพตัวอย่างที่เตรียมไว้','add-evidence')+
      `<button type="button" class="consent-choice ${m.consent?'selected':''}" ${attrs('consent')} role="checkbox" aria-checked="${m.consent}"><span class="selection-dot" aria-hidden="true">${m.consent?'✓':''}</span><span>ยินยอมให้ใช้ข้อมูลในเคสตัวอย่างเพื่อตรวจสอบและประสานงาน<small>สถานะจำลองเท่านั้น ไม่มีการส่งข้อมูลจริง</small></span></button>`+
      error(m)+button('ตรวจสอบก่อนแจ้งเหตุ','report-review');
    case 'review':return heading('ตรวจสอบการแจ้งเหตุ')+prior()+card(`${detail('เหตุการณ์',reasons[m.reason]??'ยังไม่เลือก')}${detail('ความยินยอม',m.consent?'ยืนยันในเดโมแล้ว':'ยังไม่ยืนยัน')}${detail('หลักฐาน',m.evidenceSet.size+' รายการ')}`)+
      note('หยุดเงินออกจากบัญชีของคุณแล้ว ส่วนเงินที่เคยโอนยังอยู่ระหว่างตรวจสอบ','amber')+error(m)+button('ยืนยันแจ้งเหตุจำลอง','report-send')+button('แก้ไขรายละเอียด','go','details','secondary');
    case 'submitting':return `<div class="result-mark">✓</div>`+heading('กำลังรับแจ้งเหตุ','จัดรายการตัวอย่างและหลักฐานให้เป็นเคสเดียวกัน')+`<div class="inline-progress" role="progressbar" aria-label="ความคืบหน้าการรับแจ้งเหตุ"><div id="report-progress"></div></div><p class="center muted">ขั้นตอนจำลอง · ไม่มีการส่งข้อมูลออก</p>`+button('ย้อนกลับไปตรวจสอบ','back','','secondary');
    case 'evidence':return heading('หลักฐานในเคส',`${m.evidenceSet.size} รายการ · SB-2026-00128`)+[...m.evidenceSet].map(key=>row(evidenceNames[key],'เปิดดูตัวอย่าง','evidence-open',key)).join('')+button('เลือก / เพิ่มหลักฐานตัวอย่าง','add-evidence')+button('กลับหน้าติดตามเรื่อง','track','','secondary');
    case 'addEvidence':return heading('เลือกหลักฐานตัวอย่าง','ใช้ไฟล์ตัวอย่างในเดโม ไม่มีการเลือกไฟล์จากเครื่อง')+
      Object.entries(evidenceNames).map(([key,label])=>`<button type="button" class="ui-row ${m.evidenceDraft.has(key)?'selected':''}" ${attrs('evidence-toggle',key)} aria-pressed="${m.evidenceDraft.has(key)}" data-focus="evidence-${key}"><span><strong>${label}</strong><small>ข้อมูลสมมติ · เตรียมไว้สำหรับนำเสนอ</small></span><span class="selection-dot" aria-hidden="true">${m.evidenceDraft.has(key)?'✓':''}</span></button>`).join('')+
      error(m)+button('บันทึกหลักฐานที่เลือก','evidence-save')+button('กลับโดยไม่เปลี่ยนหลักฐาน','back','','secondary');
    case 'viewer':{
      let sample='';
      if(m.viewer==='slip')sample=card(`<p class="eyebrow center">สลิปตัวอย่าง · ไม่ใช่หลักฐานธุรกรรมจริง</p><div class="result-mark small-mark">✓</div><h3 class="center">รายการโอนก่อนหน้า</h3>${detail('จำนวนเงิน','50,000.00 บาท')}${detail('ผู้รับ','ผู้รับตัวอย่าง')}${detail('บัญชีปลายทาง','xxx-x-x6789-x')}${detail('วันและเวลา','20 ก.ย. 2569 · 10:24 น.')}<p class="small muted center">ไม่มี QR หรือหมายเลขอ้างอิงที่ใช้ทำรายการจริงได้</p>`);
      if(m.viewer==='chat')sample=`<div class="sample-chat"><p class="eyebrow">ภาพบทสนทนาตัวอย่าง</p><div class="bubble other">มีเรื่องเร่งด่วน ขอให้ทำรายการตามที่แจ้ง</div><div class="bubble self">ขอตรวจสอบกับธนาคารก่อนนะคะ</div><div class="bubble other">อย่าเพิ่งวางสายหรือบอกใคร</div></div>`+note('การเร่งให้โอนและห้ามบอกผู้อื่นเป็นสัญญาณที่ควรหยุดตรวจสอบ','amber');
      if(m.viewer==='call')sample=card(`${detail('ประเภท','สายเข้าตัวอย่าง')}${detail('ผู้ติดต่อ','ผู้ติดต่อไม่รู้จัก')}${detail('ระยะเวลา','08:32 นาที')}<p>บันทึกว่ามีการเร่งให้ทำรายการและอ้างว่าเป็นเจ้าหน้าที่</p><p class="muted">ไม่มีเบอร์โทรหรือไฟล์เสียงจริง</p>`);
      if(m.viewer==='profile')sample=card(`<div class="result-mark">?</div><h3 class="center">โปรไฟล์ผู้ติดต่อตัวอย่าง</h3><p>ชื่อที่แสดง: ผู้ติดต่อสมมติ</p><p class="muted">ใช้บันทึกร่องรอยประกอบเคส ไม่ยืนยันตัวตนของผู้ติดต่อ</p>`);
      return heading(evidenceNames[m.viewer])+sample+button('กลับหน้าก่อนหน้า','back')+(m.caseSubmitted?button('ดูหลักฐานทั้งหมด','go','evidence','secondary'):'');
    }
    case 'contact':return heading('ช่วยเหลือได้ตลอด 24 ชม.','เลือกช่องทางสาธิตในแอป')+(m.caseSubmitted?caseCard(m):note('ระหว่างตรวจสอบ อย่าโอนเพิ่มหรือเปิดเผยรหัสผ่าน PIN / OTP'))+
      row('สนทนากับเจ้าหน้าที่','แชตจำลองพร้อมหัวข้อให้เลือก','chat','','›')+row('ติดต่อผ่านแอป','จำลองสถานะเชื่อมต่อ ไม่มีการโทรจริง','call')+
      row('ตรวจสถานะความปลอดภัย','การป้องกันบัญชีและอุปกรณ์','go','security')+homeButton();
    case 'chat':return `<div class="sample-chat"><div class="bubble other">สวัสดีค่ะ เจ้าหน้าที่จำลองพร้อมช่วยตรวจสอบ${m.caseSubmitted?'เคส SB-2026-00128 ':'รายการของคุณ'}ค่ะ</div><p class="small muted">เลือกหัวข้อด้านล่าง ไม่ต้องพิมพ์ข้อมูลจริง</p>${m.contactChoice?`<div class="bubble self">${m.contactChoice==='hold'?'รายการที่พักไว้จะเป็นอย่างไร?':m.contactChoice==='case'?'อยากติดตามเงินที่โอนไปก่อนหน้า':'ควรป้องกันบัญชีอย่างไร?'}</div><div class="bubble other">${m.contactChoice==='hold'?'รายการที่พักไว้ยังไม่โอนออก และไม่โอนต่อเมื่อหมดเวลาค่ะ คุณลูกค้ายกเลิกรายการ หรือเลือกแจ้งเหตุสำหรับรายการก่อนหน้าได้ค่ะ':m.contactChoice==='case'?'เคสยังอยู่ระหว่างตรวจสอบค่ะ ยังยืนยันการคืนเงินหรือการอายัดบัญชีปลายทางไม่ได้ คุณลูกค้ากดติดตามเคสหรือเตรียมหลักฐานเพิ่มได้ค่ะ':'ขอให้วางสายที่น่าสงสัยก่อนนะคะ แล้วเปิดโหมดป้องกันเพื่อหยุดเงินออกจากบัญชี และตรวจสอบกับช่องทางทางการค่ะ'}</div>`:''}</div>`+
      `<div class="choice-stack">${button('สอบถามรายการที่พักไว้','chat-choice','hold','choice')}${button('ติดตามเงินที่โอนไปก่อนหน้า','chat-choice','case','choice')}${button('ป้องกันบัญชี','chat-choice','security','choice')}</div>`+
      (m.caseSubmitted?button('ไปหน้าติดตามเคส','track'):button(m.accountProtected?'เลือกรายการแจ้งเหตุ':'เปิดโหมดฉุกเฉิน',m.accountProtected?'report-start':'emergency'))+button('จบการสนทนา','back','','secondary');
    case 'call':return `<div class="result-mark">☎</div>`+heading('เจ้าหน้าที่ช่วยเหลือ', 'ช่องทางติดต่อจำลองในแอป')+`<p id="call-state" class="call-status center"></p><div class="inline-progress"><div id="call-progress"></div></div>`+note('ไม่มีการโทรจริงหรือเปิดไมโครโฟน ข้อมูลในเคสยังอยู่ในเดโมเท่านั้น')+button('วางสายจำลอง','end-call','','danger')+button('เปลี่ยนเป็นแชตจำลอง','chat','','secondary');
    case 'security':return heading('การป้องกันบัญชี')+note(m.accountProtected?'หยุดเงินออกชั่วคราว · ยังรับเงินเข้าและดูยอดได้':'ยังไม่ได้เปิดโหมดฉุกเฉิน')+
      row('อุปกรณ์ที่เข้าสู่ระบบ',m.otherDevicesEnded?'อุปกรณ์อื่นออกจากระบบแล้ว':'ดูและจบเซสชันอุปกรณ์ตัวอย่าง','go','devices')+
      row('ตรวจความปลอดภัยของรหัส',m.passwordChecked?'ตรวจรายการแนะนำแล้ว':'ไม่มีการกรอกรหัสผ่าน PIN หรือ OTP','go','password')+
      (m.accountProtected?row('ขอคำแนะนำก่อนปลดการป้องกัน','การย้อนหน้าหรือกลับหน้าแรกไม่ปลดการป้องกัน','contact'):button('เปิดโหมดฉุกเฉิน','emergency','','danger'))+homeButton();
    case 'devices':return heading('อุปกรณ์ในตัวอย่าง')+card(`<h3>อุปกรณ์ที่กำลังใช้</h3><p>เครื่องปัจจุบัน · อยู่ในเดโม</p>`)+card(`<h3>อุปกรณ์อื่น 1 เครื่อง</h3><p>${m.otherDevicesEnded?'ออกจากระบบแล้ว':'มีเซสชันตัวอย่างที่ยังเปิดอยู่'}</p>`)+(m.otherDevicesEnded?note('จบเซสชันอื่นในสถานะจำลองแล้ว'):button('ออกจากระบบบนอุปกรณ์อื่น','devices-end'))+button('กลับหน้าความปลอดภัย','go','security','secondary');
    case 'password':return heading('ตรวจความปลอดภัย')+card(`<ul class="checklist"><li>ไม่บอกรหัสผ่าน PIN หรือ OTP ให้ผู้อื่น</li><li>ตรวจอุปกรณ์ที่เคยเข้าสู่ระบบ</li><li>เปลี่ยนรหัสผ่านช่องทางทางการเมื่อจำเป็น</li></ul>`)+note('หน้านี้ไม่รับหรือเปลี่ยนรหัสจริง ใช้ตรวจรายการแนะนำในเดโมเท่านั้น')+button('ทำเครื่องหมายว่าตรวจแล้ว','password-check')+button('ดูอุปกรณ์ที่เข้าสู่ระบบ','go','devices','secondary');
    case 'nextSteps':return heading('สิ่งที่ทำต่อได้')+(m.caseSubmitted?caseCard(m):note('ยังไม่มีเคสที่แจ้งในเดโม'))+
      row('1. เก็บหลักฐาน',`${m.evidenceSet.size} รายการพร้อมในเคส`,'go',m.caseSubmitted?'evidence':'transactions')+
      row('2. ติดต่อเจ้าหน้าที่','สอบถามผ่านช่องทางทางการ','contact')+
      row('3. เตรียมข้อมูลแจ้ง AOC 1441',m.aocPrepared?'เตรียมข้อมูลตัวอย่างแล้ว · ยังไม่ได้ส่ง':'เมื่อเจ้าหน้าที่ตรวจสอบข้อมูลเบื้องต้นแล้ว','go','aoc')+
      row('4. ตรวจความปลอดภัยบัญชี',m.accountProtected?'การป้องกันยังเปิดอยู่':'ดูคำแนะนำและอุปกรณ์','go','security')+homeButton();
    case 'aoc':return heading('เตรียมข้อมูลแจ้ง AOC 1441')+card(`${detail('เลขเคส',m.caseSubmitted?'SB-2026-00128':'ยังไม่ได้แจ้งเหตุ')}${detail('รายการก่อนหน้า','50,000.00 บาท')}${detail('หลักฐานที่เตรียม',m.evidenceSet.size+' รายการ')}`)+note('เดโมแสดงเพียงการเตรียมข้อมูล ไม่มีการโทรหรือส่งข้อมูลไป AOC และไม่ยืนยันการอายัดบัญชีปลายทาง','amber')+button('ทำเครื่องหมายว่าเตรียมข้อมูลแล้ว','aoc-ready')+button('ติดต่อเจ้าหน้าที่เพื่อตรวจสอบก่อน','contact','','secondary');
    case 'account':return heading('บัญชีของฉัน','xxx-x-x2560-x')+card(`<p class="muted">ยอดคงเหลือในตัวอย่าง</p><p class="money">${m.balanceVisible?money(m.balanceCents):'••••••'} <small>บาท</small></p>${button(m.balanceVisible?'ซ่อนยอดเงิน':'แสดงยอดเงินตัวอย่าง','balance','','secondary')}`)+note(m.accountProtected?'บัญชีอยู่ในโหมดป้องกัน ยังดูยอดและรับเงินเข้าได้':'รายการที่พักไว้ยังไม่หักยอดคงเหลือ')+button('ดูรายการธุรกรรม','go','transactions')+button('โอนเงิน','transfer','','secondary')+homeButton();
    case 'notifications':return heading('แจ้งเตือน')+(m.caseSubmitted?row('รับแจ้งเหตุแล้ว · SB-2026-00128','ติดตามสถานะกำลังตรวจสอบ','track'):'')+(m.accountProtected?row('เปิดโหมดป้องกันบัญชีแล้ว','ดูสถานะหยุดเงินออกและอุปกรณ์','go','security'):'')+(m.amountCents>0?row('อัปเดตรายการที่กำลังทำ',m.transferStatus==='cancelled'?'ยกเลิกรายการแล้ว':'รายการยังไม่มีเงินโอนออก','transaction','pending'):'')+row('รู้ทันก่อนโอน','เริ่มโอนตัวอย่างและลองฟีเจอร์เบรกก่อนโอน','transfer')+homeButton();
    case 'services':return heading('บริการและความช่วยเหลือ')+row('โอนเงิน','เริ่มรายการตัวอย่างใหม่','transfer')+row('ธุรกรรมของฉัน','รายการก่อนหน้าและรายการที่พักไว้','go','transactions')+row('ScamBreak','ขอความช่วยเหลือเมื่อสงสัยว่าถูกหลอก','emergency')+row('ติดตามเรื่อง',m.caseSubmitted?'SB-2026-00128':'ดูรายการก่อนเริ่มแจ้งเหตุ','track')+row('ความปลอดภัย','อุปกรณ์และการป้องกันบัญชี','go','security')+row('ติดต่อเจ้าหน้าที่','แชต / โทรในสถานะจำลอง','contact')+homeButton();
    case 'service':{const service=services[m.serviceKind];return heading(service.title+'ตัวอย่าง','ใช้ผู้รับและข้อมูลที่เตรียมไว้เท่านั้น')+card(`<h3>${service.recipient}</h3><p class="muted">ไม่มีการกรอกเบอร์โทร เลขบิล หรือข้อมูลจริง</p>`)+`<p class="eyebrow">เลือกจำนวนเงิน</p><div class="preset-row">${service.amounts.map(v=>button(v.toLocaleString('en-US')+' บาท','service-amount',String(v),`chip ${m.serviceAmount===v*100?'selected':''}`,`aria-pressed="${m.serviceAmount===v*100}"`)).join('')}</div><p class="money center">${money(m.serviceAmount)} <small>บาท</small></p>`+button('ตรวจสอบรายการ','service-next')+homeButton();}
    case 'serviceReview':return heading('ตรวจสอบ'+services[m.serviceKind].title)+card(`${detail('รายการ',services[m.serviceKind].recipient)}${detail('จำนวนเงิน',money(m.serviceAmount)+' บาท')}${detail('ค่าธรรมเนียม','0.00 บาท')}`)+note('ยืนยันเฉพาะสถานะและยอดคงเหลือในเดโม ไม่มีการจ่ายเงินจริง')+error(m)+button('ยืนยันรายการจำลอง','service-confirm')+button('แก้ไขจำนวนเงิน','back','','secondary');
    case 'serviceDone':return `<div class="result-mark">✓</div>`+heading('รายการตัวอย่างสำเร็จ','ไม่มีการทำธุรกรรมจริง')+card(`${detail('บริการ',services[m.serviceKind].title)}${detail('จำนวนเงิน',money(m.serviceAmount)+' บาท')}${detail('อ้างอิงในเดโม','SERVICE-'+m.serviceReceipts.length)}`)+(m.serviceKind==='withdraw'?note('ไม่สร้างรหัสที่ใช้ถอนเงินจริงที่ตู้ ATM ได้'):note('รายการนี้ถูกเพิ่มในประวัติของเดโมแล้ว'))+button('ดูรายการธุรกรรม','go','transactions')+homeButton();
    case 'scan':return heading('สแกน QR ตัวอย่าง','ไม่เปิดกล้องและไม่อ่าน QR จากภายนอก')+`<div class="scan-sample" aria-hidden="true"><span>QR<br><small>ตัวอย่าง</small></span></div>`+note('เลือก QR ตัวอย่างเพื่อระบุยอดและตรวจสอบความเสี่ยงในเส้นทางเดียวกับการโอน')+button('ใช้ QR ตัวอย่างของผู้รับ','scan-sample')+homeButton();
    case 'blocked':return `<div class="result-mark">✓</div>`+heading('บัญชีอยู่ในโหมดป้องกัน','หยุดเงินออกจากบัญชีของคุณแล้ว')+note('ยังรับเงินเข้าและดูยอดได้ แต่ไม่ทำรายการเงินออกเพิ่มเติมในเดโมจนกว่าจะเริ่มใหม่')+button('ดูสถานะป้องกันบัญชี','go','emergency')+button(m.caseSubmitted?'ติดตามเคส':'เลือกรายการแจ้งเหตุ',m.caseSubmitted?'track':'report-start','','secondary')+button('ติดต่อเจ้าหน้าที่','contact','','secondary')+homeButton();
    default:return '';
  }
}

export function caption(m){
  if(m.notice)return m.notice;
  if(m.cue)return m.cue.caption;
  const descriptions={home:'เริ่มด้วย “โอนเงิน” หรือขอความช่วยเหลือจาก “ฉันอาจถูกหลอก”',recipient:'ใช้ผู้รับสมมติเดิมจากสไลด์ ไม่ต้องกรอกเลขบัญชีจริง',amount:'ใส่ยอดด้วยแป้นตัวเลขหรือพิมพ์ได้ แล้วตรวจสอบรายการ',confirm:'ตรวจสอบผู้รับและยอดที่คุณใส่ แล้วกดตรวจสอบความเสี่ยง',questions:'เลือกคำตอบครบ 3 ข้อ แล้วดูคำแนะนำ',hold:m.countdown?'รายการที่กำลังทำยังไม่โอนออก · ตั้งสติ วางสาย แล้วตรวจสอบ':'หมดเวลาแล้ว รายการยังพักไว้ · ไม่โอนต่ออัตโนมัติ',emergency:'หยุดเงินออกจากบัญชีผู้ใช้ · เงินที่โอนไปก่อนหน้ายังต้องตรวจสอบ',select:'เลือกเฉพาะรายการก่อนหน้าที่โอนไปแล้ว รายการที่พักไว้ไม่มีเงินออก',details:'ระบุเหตุการณ์และความยินยอมจากตัวอย่าง ก่อนตรวจทาน',review:'ยืนยันแล้วจึงสร้างเคสจำลอง ไม่มีการส่งข้อมูลจริง',tracking:'SB-2026-00128 · กำลังตรวจสอบ ไม่ได้ยืนยันว่าได้เงินคืน',cancelled:'ยกเลิกเฉพาะรายการที่พักไว้ เงินไม่ถูกโอนออก',blocked:'โหมดป้องกันยังคงอยู่แม้เปลี่ยนหน้า',serviceDone:'รายการเสร็จสิ้นในหน่วยความจำของเดโมเท่านั้น'};
  return descriptions[m.route]??'ทุกข้อมูลและการติดต่อเป็นสถานะจำลอง · ย้อนกลับหรือกลับหน้าแรกได้';
}
